### PR TITLE
Add lever and door system

### PR DESCRIPTION
**Pull request by Lmh-java**
1. Add IInteractable and ILeverController interfaces
2. Add LeverAndDoorsScene

### Resolved Issues
#50 

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions and classes should have some sort of basic JavaDoc comments. use `///` to generate XMLDocs for C# using IDE.
- [X] **Remove all commented out code**
- [X] **Remove extra print statements**: for example, those just used for testing
- [X] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [X] **Play Mode Runs**

### CODE REVIEW

**Review by Andrewyx — COMMENTED** [review]
LGTM so far. Keep in mind that the floor area as of now is not labelled as the ground layer so jumping has been disabled. 

Otherwise, there are really only two additional small details that we discussed regarding this feature in the meeting today:
1) There should be a way to re-toggle the door to re-enable it with another lick. 
2) We should be able to toggle the lever by running into it from different directions.

Lastly, do you know if the lever's behaviour and animation is still the same if we rotate it and place it against a wall/roof instead of being on the floor?

**Comment by Lmh-java** [comment]
Q1 won't be a problem, just add 3 additional lines
Q2 will be a bit complex but I will try, gimme some time
Q3: it works fine in every direction rn, no watter it's on the wall or the ground.

btw, ```Keep in mind that the floor area as of now is not labelled as the ground layer so jumping has been disabled.```, why does this matter for this PR. I don't think I get it.

**Review by TMZero-c — APPROVED** [review]
- There a glitch where if player is next to the door, it can go through and touch the lever
- Also the door is not closable, opens only once and stays at that state, would be nice to make it be able to close again for puzzles
- lgtm

**Comment by Lmh-java** [comment]
@TMZero-c No worries about the glitch, I guess it's because the door is too small. But what is done in this PR is all about prefabs and a demo scene. Level designers can handle these issues by scaling the door?

Also, pls don't merge this PR yet, I am still testing the tongue function, the original one is limited. I'll mark this as draft.

**Pull request merged**
